aws_region = "ap-south-1"
# vpc_name                         = "kubikk-test"
kubikk_deployment_name           = "kubikk-test"
vpc_cidr                         = "20.10.0.0/16"
dhcp_options_domain_name         = "example.com"
dhcp_options_domain_name_servers = ["127.0.0.1", "10.10.10.2"]
private_subnet_count             = 2
public_subnet_count              = 2
private_subnet_cidrs             = ["20.10.1.0/24", "20.10.2.0/24"]
public_subnet_cidrs              = ["20.10.11.0/24", "20.10.12.0/24"]
az_list                          = ["ap-south-1a", "ap-south-1b", "ap-south-1c"]
enable_dhcp_options              = true
enable_dns_hostnames             = true
enable_dns_support               = true
enable_nat_gateway               = true
single_nat_gateway               = true
one_nat_gateway_per_az           = false
ami                              = "ami-0ffc7af9c06de0077"
k8s_master_instance_type         = "t2.micro"
number_of_k8s_masters            = 1
